services:
  - type: web
    name: pathquest-backend
    runtime: docker
    repo: https://github.com/Dhriti-1312/path_finding_visualizer
    branch: main
    rootDir: backend
    plan: free
    dockerfilePath: backend/Dockerfile
